enable-tracing = true

[store]
  name = "newtikv"
  path = "tikv://192.168.30.22:2379,192.168.30.23:2379,192.168.30.24:2379"
  gc-enable = false
  pd-address = []
  read-timeout = "10s"
  list-timeout = "1m0s"
  write-timeout = "10s"
  batch-put-timeout = "1m0s"
  batch-delete-timeout = "10m0s"

[server]
  http-host = "192.168.14.101"
  http-port = 6100
  replica-read = false
  read-timeout = "10s"
  conn-timeout = "1s"
  read-header-timeout = "5s"
  write-timeout = "10s"
  idle-timeout = "2m0s"
  sleep-before-close = "5s"

[connector]
  name = "kafka"
  version = "2.5.0"
  enable-producer = true
  debug-producer = false
  broker-list = ["192.168.30.100:9092", "192.168.30.101:9092", "192.168.30.102:9092","192.168.30.103:9092","192.168.30.104:9092"]
  fetch-metadata = true
  entry = 10000
  topic = "tikvmeta"
  partition-num = 512
  queue-data-path = "/disk/ssd6/tikv-proxy/queue/"
  mem-queue-size = 10000
  max-bytes-per-file = 104857600
  sync-every = 1000
  max-msg-size = 1048576
  back-off = "250ms"
  max-back-off = "1m0s"
  sync-timeout = "2s"
  write-timeout = "50ms"

[log]
  level = "info"
  error-log-dir = "/disk/ssd6/tikv-proxy/logs/error.log"
  access-log-dir = "/disk/ssd6/tikv-proxy/logs/access.log"
  buffer-size = 102400
  max-bytes = 536870912
  backup_count = 10
