ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = -1
warningCode = -1

[rule.blank-imports]
[rule.context-as-argument]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
#[rule.exported]
[rule.if-return]
#[rule.var-naming]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.indent-error-flow]
[rule.superfluous-else]
[rule.modifies-parameter]

[rule.unreachable-code]

[rule.confusing-naming]
  severity = "warning"
[rule.confusing-results]
  severity = "warning"
[rule.unused-parameter]
  severity = "warning"
[rule.deep-exit]
  severity = "warning"
#[rule.flag-parameter]
#  severity = "warning"

[rule.unexported-return]
[rule.time-naming]
[rule.errorf]
[rule.var-declaration]
[rule.context-keys-type]
